### ISSUE TITLE
Make it bubble up the error instead of printing to stdout

### ISSUE THREAD

**Issue by Mastermindaxe** [giripriyadarshan/inputparser#2]
Instead of just printing out to stdout I'd suggest instead letting the user work with the error through bubbling the error up. This way I can decide what to do when false input is provided.
The way it is now gives me no leeway on what to do with the error

**Comment by giripriyadarshan** [comment]
Version 0.1.70 kind of addresses it ..... if any other functionalities are missing, please let me know ..... Thank you :heart:
